version: "2"

services:

  sonarqube:
    image: sonarqube:5.6.6-alpine
    restart: always
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - ../sonarqube/sonar.properties:/opt/sonarqube/conf/sonar.properties
    volumes_from:
      - sonarqube-data
    depends_on:
      - sonarqube-data
      - sonarqube-db

  sonarqube-data:
    image: busybox
    volumes:
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions
      - /opt/sonarqube/lib/bundled-plugins

  sonarqube-db:
    image: postgres:9.5.7-alpine
    restart: always
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes_from:
      - sonarqube-db-data
    depends_on:
      - sonarqube-db-data

  sonarqube-db-data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
